### PR TITLE
HSC-330: Added release notes for version 1.8.2

### PR DESCRIPTION
**Pull request by kazlaw**
Ticket: https://mekomsolutions.atlassian.net/browse/HSC-325

### CODE REVIEW

**Review by Ruhanga — COMMENTED** [review]
@kazlaw was there openmrs-config-hsc changes?

**Comment by kazlaw** [comment]
No: https://mekomsolutions.atlassian.net/browse/HSC-304?focusedCommentId=45459

**Comment by kazlaw** [comment]
> @kazlaw was there openmrs-config-hsc changes?

Let me confirm @Ruhanga

**Comment by kazlaw** [comment]
File updated as shared here:https://mekomsolutions.slack.com/archives/G421UNF5L/p1728919245861259?thread_ts=1728917210.042509&cid=G421UNF5L

**Pull request merged**
